apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jppod002-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jppod002
  template:
    metadata:
      labels:
        app: jppod002
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: jppod002-service
spec:
  selector:
    app: jppod002
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
