apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jppod002-replicaset
spec:
  replicas: 10
  selector:
    matchLabels:
      app: jppod002
  template:
    metadata:
      labels:
        app: jppod002
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
