---
apiVersion: v1
kind: Pod
metadata:
  name: jppod002
  labels:
    app: jppod002
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: lbsrvc
spec:
  type: LoadBalancer
  selector:
    app: jppod002
  ports:
    - name: http
      port: 8080
      targetPort: 80
